In [1]:
import pandas as pd
import numpy as np

In [33]:
holdings = pd.read_excel('../data/holdings-CY7213.xlsx',sheet_name='Equity')

In [45]:
def get_holdings(holdings):
    new_headers = holdings.iloc[21]
    df = holdings.iloc[22:,1:]
    df.columns = new_headers[1:]
    return df

In [46]:
# get the equity holdings
equity = get_holdings(holdings)

In [47]:
equity

21,Symbol,ISIN,Sector,Quantity Available,Quantity Discrepant,Quantity Long Term,Quantity Pledged (Margin),Quantity Pledged (Loan),Average Price,Previous Closing Price,Unrealized P&L,Unrealized P&L Pct.
22,ADANIGREEN,INE364U01010,Utilities,10.0,0.0,0.0,0.0,0.0,1174.88,1935.3,7604.2,64.7232
23,ADANIPOWER,INE814H01011,Utilities,50.0,0.0,0.0,0.0,0.0,111.85,110.0,-92.5,-1.654
24,BANKBARODA,INE028A01039,Financials,10.0,0.0,0.0,0.0,0.0,91.975,92.7,7.25,0.7883
25,BEL,INE263A01024,Industrials,34.0,0.0,0.0,0.0,0.0,193.05,206.95,472.6,7.2002
26,BPCL,INE029A01011,Energy,10.0,0.0,0.0,0.0,0.0,450.6,381.7,-689.0,-15.2907
27,BSOFT,INE836A01035,Information Technology,2.0,0.0,0.0,0.0,0.0,540.3,487.75,-105.1,-9.7261
28,CANBK,INE476A01014,Financials,108.0,0.0,0.0,0.0,0.0,212.537,215.6,330.8,1.4411
29,COALINDIA,INE522F01014,Energy,23.0,0.0,0.0,0.0,0.0,166.9043,158.75,-187.55,-4.8856
30,DEEPAKNTR,INE288B01029,Materials,17.0,0.0,0.0,0.0,0.0,2557.0735,2500.95,-954.1,-2.1948
31,DELTACORP,INE124G01033,Consumer Discretionary,50.0,0.0,0.0,0.0,0.0,230.53,286.55,2801.0,24.3005
32,FSL,INE684F01012,Information Technology,9.0,0.0,0.0,0.0,0.0,180.9222,163.85,-153.65,-9.4362
33,HAPPSTMNDS-T,INE419U01012,Others,2.0,0.0,0.0,0.0,0.0,1279.05,1250.2,-57.7,-2.2556
34,HDFCBANK,INE040A01034,Financials,3.0,0.0,0.0,0.0,0.0,1522.35,1521.6,-2.25,-0.0493
35,IDBI,INE008A01015,Financials,24.0,0.0,0.0,0.0,0.0,48.6708,48.7,0.7,0.0599
36,IOC,INE242A01010,Energy,46.0,0.0,0.0,0.0,0.0,117.1043,121.7,211.4,3.9244
37,IRCTC,INE335Y01020,Industrials,5.0,0.0,0.0,0.0,0.0,744.51,861.7,585.95,15.7406
38,JPPOWER,INE351F01018,Utilities,1200.0,0.0,0.0,0.0,0.0,5.5917,9.61,4822.0,71.8629
39,JSWENERGY-T,INE121E01018,Utilities,20.0,0.0,0.0,0.0,0.0,392.375,308.85,-1670.5,-21.287
40,JUNIORBEES,INF732E01045,Others,3.0,0.0,0.0,0.0,0.0,444.5367,443.75,-2.36,-0.177
41,NHPC,INE848E01016,Utilities,250.0,0.0,0.0,0.0,0.0,26.821,30.45,907.25,13.5304
42,NIFTYBENAV,INF204KB14I2,Others,24.0,0.0,0.0,0.0,0.0,187.3237,190.64,79.59,1.7703
43,NTPC,INE733E01010,Utilities,56.0,0.0,0.0,0.0,0.0,120.0875,134.1,784.7,11.6686
44,NYKAA,INE388Y01029,Others,4.0,0.0,0.0,0.0,0.0,2223.85,1998.3,-902.2,-10.1423
45,PIDILITIND,INE318A01026,Materials,4.0,0.0,0.0,0.0,0.0,2425.0,2700.6,1102.4,11.3649
46,PNB,INE160A01022,Financials,28.0,0.0,0.0,0.0,0.0,39.1464,38.8,-9.7,-0.885
47,POWERGRID,INE752E01010,Utilities,40.0,0.0,0.0,0.0,0.0,199.0,215.1,644.0,8.0905
48,RELAXO,INE131B01039,Consumer Discretionary,10.0,0.0,0.0,0.0,0.0,1221.08,1316.25,951.7,7.7939
49,RELIANCE,INE002A01018,Energy,19.0,0.0,0.0,0.0,0.0,2134.7947,2478.1,6522.8,16.0814
50,SBIN,INE062A01020,Financials,2.0,0.0,0.0,0.0,0.0,495.975,502.8,13.65,1.3761
51,SONATSOFTW,INE269A01021,Information Technology,1.0,0.0,0.0,0.0,0.0,858.8,860.7,1.9,0.2212
52,TANLA,INE483C01032,Information Technology,1.0,0.0,0.0,0.0,0.0,1835.9,1875.1,39.2,2.1352
53,TATAMOTORS,INE155A01022,Consumer Discretionary,29.0,0.0,0.0,0.0,0.0,467.769,502.0,992.7,7.3179
54,TATAPOWER,INE245A01021,Utilities,18.0,0.0,0.0,0.0,0.0,225.3083,242.05,301.35,7.4306
55,TATASTEEL,INE081A01012,Materials,5.0,0.0,0.0,0.0,0.0,1358.3,1169.7,-943.0,-13.885
56,TCS,INE467B01029,Information Technology,21.0,0.0,5.0,0.0,0.0,3360.5905,3834.85,9959.45,14.1124
57,TVSMOTOR,INE494B01023,Consumer Discretionary,10.0,0.0,0.0,0.0,0.0,709.75,631.7,-780.5,-10.9968
58,YESBANK,INE528G01035,Financials,100.0,0.0,0.0,0.0,0.0,12.98,13.75,77.0,5.9322

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime

# Assuming you have a DataFrame 'df' with your portfolio data
# You can read data from the database using appropriate methods

# Sample data loading (replace this with your database query)
# df = pd.read_sql_query("SELECT * FROM your_table;", your_database_connection)

# Sample DataFrame creation for illustration purposes
data = {
    'id': [1, 2, 3],
    'average_price': [100, 50, 75],
    'isin': ['ISIN1', 'ISIN2', 'ISIN3'],
    'previous_closing_price': [110, 45, 70],
    'quantity_available': [100, 200, 150],
    'quantity_discrepant': [5, 10, 8],
    'quantity_long_term': [20, 30, 25],
    'quantity_pledged_loan': [0, 15, 5],
    'quantity_pledged_margin': [10, 20, 15],
    'record_date': ['2023-01-01', '2023-01-02', '2023-01-03'],
    'sector': ['Tech', 'Finance', 'Health'],
    'symbol': ['AAPL', 'JPM', 'PFE'],
    'unrealized_pl': [500, -200, 100],
    'unrealized_pl_pct': [0.05, -0.04, 0.02],
    'load_dt': ['2023-01-05', '2023-01-05', '2023-01-05'],
    'user_name': ['user1', 'user2', 'user3'],
    'created_by': ['script', 'script', 'script']
}

df = pd.DataFrame(data)
df['record_date'] = pd.to_datetime(df['record_date'])
df['load_dt'] = pd.to_datetime(df['load_dt'])

In [3]:
df

,id,average_price,isin,previous_closing_price,quantity_available,quantity_discrepant,quantity_long_term,quantity_pledged_loan,quantity_pledged_margin,record_date,sector,symbol,unrealized_pl,unrealized_pl_pct,load_dt,user_name,created_by
0,1,100,ISIN1,110,100,5,20,0,10,2023-01-01,Tech,AAPL,500,0.05,2023-01-05,user1,script
1,2,50,ISIN2,45,200,10,30,15,20,2023-01-02,Finance,JPM,-200,-0.04,2023-01-05,user2,script
2,3,75,ISIN3,70,150,8,25,5,15,2023-01-03,Health,PFE,100,0.02,2023-01-05,user3,script

In [4]:

# # Calculate daily returns
# df['daily_return'] = df.groupby('isin')['previous_closing_price'].pct_change()

# # Calculate portfolio value for each day
# df['portfolio_value'] = df['average_price'] * df['quantity_available']

# # Calculate portfolio returns
# df['portfolio_return'] = df.groupby('isin')['portfolio_value'].pct_change()

# # Calculate portfolio volatility
# portfolio_volatility = df.groupby('isin')['portfolio_return'].std()

# # Calculate beta (using the covariance with a market index)
# market_index_returns = pd.Series([0.01, 0.02, 0.01], index=df['record_date'].unique())
# cov_matrix = np.cov(df['portfolio_return'].dropna(), market_index_returns.dropna())
# beta = cov_matrix[0, 1] / market_index_returns.var()

# # Calculate Sharpe ratio
# risk_free_rate = 0.02  # Adjust with the actual risk-free rate
# sharpe_ratio = (df['portfolio_return'].mean() - risk_free_rate) / portfolio_volatility.mean()

# # Display results
# print(f"Portfolio Volatility:\n{portfolio_volatility}\n")
# print(f"Beta: {beta}\n")
# print(f"Sharpe Ratio: {sharpe_ratio}")

In [5]:
df['daily_return'] = df.groupby('isin')['previous_closing_price'].pct_change()

In [6]:
df

,id,average_price,isin,previous_closing_price,quantity_available,quantity_discrepant,quantity_long_term,quantity_pledged_loan,quantity_pledged_margin,record_date,sector,symbol,unrealized_pl,unrealized_pl_pct,load_dt,user_name,created_by,daily_return
0,1,100,ISIN1,110,100,5,20,0,10,2023-01-01,Tech,AAPL,500,0.05,2023-01-05,user1,script,NaN
1,2,50,ISIN2,45,200,10,30,15,20,2023-01-02,Finance,JPM,-200,-0.04,2023-01-05,user2,script,NaN
2,3,75,ISIN3,70,150,8,25,5,15,2023-01-03,Health,PFE,100,0.02,2023-01-05,user3,script,NaN

In [1]:
import yfinance as yf

In [2]:
data = {'symbol':'BDL', 'buyprice': 100, 'target': 1260, 'recommendationdate': '2023-11-28'}

In [3]:
tick = yf.Ticker(data['symbol']+'.NS')

In [4]:
tick.info

{'address1': 'Plot No. 38-39, TSFC Building',
 'address2': 'Near ICICI Towers Financial District, Nanakramguda Gachibowli',
 'city': 'Hyderabad',
 'zip': '500032',
 'country': 'India',
 'phone': '91 40 2345 6145',
 'fax': '91 40 2345 6107',
 'website': 'https://bdl-india.in',
 'industry': 'Aerospace & Defense',
 'industryKey': 'aerospace-defense',
 'industryDisp': 'Aerospace & Defense',
 'sector': 'Industrials',
 'sectorKey': 'industrials',
 'sectorDisp': 'Industrials',
 'longBusinessSummary': 'Bharat Dynamics Limited engages in the manufacturing and sale of guided missiles and allied equipment in India. It provides surface to air, air-to-air, and anti-tank guided missiles, as well as underwater weapons, launchers, counter measures dispensing systems, test equipment, torpedoes, mechanized infantry weapons, allied defense equipments, anti-submarine warfare suite, etc. The company offers its products to the Indian Armed forces and government of India. It also exports its products. Bharat Dynamics Limited was incorporated in 1970 and is headquartered in Hyderabad, India.',
 'fullTimeEmployees': 2549,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Commodore A.  Madhavarao',
   'title': 'Chairman & MD',
   'fiscalYear': 2023,
   'totalPay': 4847545,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Nuka  Srinivasulu',
   'age': 58,
   'title': 'Director of Finance, CFO & Whole Time Director',
   'yearBorn': 1964,
   'fiscalYear': 2023,
   'totalPay': 5788352,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Nagula  Nagaraja',
   'title': 'Company Secretary & Compliance Officer',
   'fiscalYear': 2023,
   'totalPay': 2657465,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Commodore Trilok Nath Kaul',
   'title': 'Executive Director of Marketing',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. N. Sampath Kumar',
   'title': 'GM & Unit Head of IBU',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sivanand. S Khanapet',
   'title': 'Executive Director & Head of BU',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Syed  Raffe',
   'title': 'General Manager of HR',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Dr. Upender  Vennam',
   'title': 'Chief Vigilance Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. P V Raja Ram',
   'title': 'Director of Production & Director',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'compensationAsOfEpochDate': 1703980800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 1162.75,
 'open': 1192.0,
 'dayLow': 1185.05,
 'dayHigh': 1231.0,
 'regularMarketPreviousClose': 1162.75,
 'regularMarketOpen': 1192.0,
 'regularMarketDayLow': 1185.05,
 'regularMarketDayHigh': 1231.0,
 'dividendRate': 9.35,
 'dividendYield': 0.0076,
 'exDividendDate': 1695168000,
 'payoutRatio': 0.4027,
 'fiveYearAvgDividendYield': 2.12,
 'beta': 0.578,
 'trailingPE': 52.639725,
 'forwardPE': 27.269487,
 'volume': 3017472,
 'regularMarketVolume': 3017472,
 'averageVolume': 736117,
 'averageVolume10days': 1148909,
 'averageDailyVolume10Day': 1148909,
 'bid': 0.0,
 'ask': 0.0,
 'bidSize': 0,
 'askSize': 0,
 'marketCap': 224537821184,
 'fiftyTwoWeekLow': 787.0,
 'fiftyTwoWeekHigh': 1278.0,
 'priceToSalesTrailing12Months': 10.331453,
 'fiftyDayAverage': 1044.372,
 'twoHundredDayAverage': 1062.499,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'INR',
 'enterpriseValue': 186196164608,
 'profitMargins': 0.19574,
 'floatShares': 45327817,
 'sharesOutstanding': 183280992,
 'heldPercentInsiders': 0.74926,
 'heldPercentInstitutions': 0.15275,
 'impliedSharesOutstanding': 183386000,
 'bookValue': 184.159,
 'priceToBook': 6.648603,
 'lastFiscalYearEnd': 1680220800,
 'nextFiscalYearEnd': 1711843200,
 'mostRecentQuarter': 1696032000,
 'earningsQuarterlyGrowth': 0.94,
 'netIncomeToCommon': 4254125056,
 'trailingEps': 23.26,
 'forwardEps': 44.9,
 'enterpriseToRevenue': 8.567,
 'enterpriseToEbitda': 50.155,
 '52WeekChange': 0.27276504,
 'SandP52WeekChange': 0.1422813,
 'lastDividendValue': 1.2,
 'lastDividendDate': 1695168000,
 'exchange': 'NSI',
 'quoteType': 'EQUITY',
 'symbol': 'BDL.NS',
 'underlyingSymbol': 'BDL.NS',
 'shortName': 'BHARAT DYNAMICS LT',
 'longName': 'Bharat Dynamics Limited',
 'firstTradeDateEpochUtc': 1521776700,
 'timeZoneFullName': 'Asia/Kolkata',
 'timeZoneShortName': 'IST',
 'uuid': '4ee35892-4d73-319d-bd26-5da3c597b19d',
 'messageBoardId': 'finmb_23006716',
 'gmtOffSetMilliseconds': 19800000,
 'currentPrice': 1224.4,
 'targetHighPrice': 1420.0,
 'targetLowPrice': 1215.0,
 'targetMeanPrice': 1338.33,
 'targetMedianPrice': 1342.5,
 'recommendationMean': 1.4,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 6,
 'totalCash': 38133977088,
 'totalCashPerShare': 208.178,
 'ebitda': 3712412928,
 'totalDebt': 44919000,
 'quickRatio': 2.403,
 'currentRatio': 4.408,
 'totalRevenue': 21733421056,
 'debtToEquity': 0.133,
 'revenuePerShare': 118.608,
 'returnOnAssets': 0.02379,
 'returnOnEquity': 0.13087,
 'grossProfits': 12681743000,
 'freeCashflow': -10798296064,
 'operatingCashflow': 19093815296,
 'earningsGrowth': 0.94,
 'revenueGrowth': 0.152,
 'grossMargins': 0.56831,
 'ebitdaMargins': 0.17082001,
 'operatingMargins': 0.18935,
 'financialCurrency': 'INR',
 'trailingPegRatio': None}

In [7]:
tick.history(period='1d', interval='15m')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2023-12-01 09:15:00+05:30,1193.050049,1206.949951,1185.050049,1191.599976,288154,0.0,0.0
2023-12-01 09:30:00+05:30,1191.000000,1201.000000,1189.199951,1199.949951,111898,0.0,0.0
2023-12-01 09:45:00+05:30,1198.050049,1217.000000,1197.550049,1208.500000,745213,0.0,0.0
2023-12-01 10:00:00+05:30,1208.500000,1213.000000,1207.199951,1210.400024,93634,0.0,0.0
2023-12-01 10:15:00+05:30,1210.000000,1211.750000,1198.000000,1200.000000,131316,0.0,0.0
2023-12-01 10:30:00+05:30,1200.599976,1200.900024,1187.150024,1197.449951,104902,0.0,0.0
2023-12-01 10:45:00+05:30,1197.699951,1202.699951,1193.550049,1201.000000,45564,0.0,0.0
2023-12-01 11:00:00+05:30,1201.000000,1202.000000,1199.000000,1202.000000,26248,0.0,0.0
2023-12-01 11:15:00+05:30,1201.050049,1206.599976,1200.400024,1202.650024,50622,0.0,0.0
2023-12-01 11:30:00+05:30,1203.000000,1203.000000,1200.000000,1201.949951,23755,0.0,0.0
2023-12-01 11:45:00+05:30,1200.750000,1203.000000,1198.599976,1198.599976,24013,0.0,0.0
2023-12-01 12:00:00+05:30,1197.199951,1201.250000,1197.000000,1199.949951,21507,0.0,0.0
2023-12-01 12:15:00+05:30,1199.949951,1202.500000,1199.050049,1202.449951,19557,0.0,0.0
2023-12-01 12:30:00+05:30,1202.449951,1204.949951,1200.900024,1202.000000,35066,0.0,0.0
2023-12-01 12:45:00+05:30,1202.000000,1204.300049,1200.199951,1203.400024,24899,0.0,0.0
2023-12-01 13:00:00+05:30,1203.900024,1204.300049,1201.550049,1203.500000,32356,0.0,0.0
2023-12-01 13:15:00+05:30,1203.650024,1204.300049,1202.000000,1202.800049,26588,0.0,0.0
2023-12-01 13:30:00+05:30,1203.000000,1204.300049,1202.400024,1203.050049,22034,0.0,0.0
2023-12-01 13:45:00+05:30,1203.949951,1207.000000,1203.099976,1205.000000,36343,0.0,0.0
2023-12-01 14:00:00+05:30,1205.949951,1211.949951,1203.500000,1208.900024,60266,0.0,0.0
2023-12-01 14:15:00+05:30,1209.300049,1212.000000,1207.000000,1210.000000,56125,0.0,0.0
2023-12-01 14:30:00+05:30,1210.000000,1216.599976,1208.250000,1215.449951,166650,0.0,0.0
2023-12-01 14:45:00+05:30,1215.449951,1224.000000,1215.000000,1222.099976,248076,0.0,0.0
2023-12-01 15:00:00+05:30,1222.750000,1230.949951,1221.150024,1223.000000,271496,0.0,0.0
2023-12-01 15:15:00+05:30,1223.599976,1226.699951,1216.000000,1218.000000,186238,0.0,0.0

In [8]:
tick.history(period='1d', interval='15m',).tail(1)['Close'][0]

1218.0

In [10]:
tick.history(start='2023-10-28',interval='60m')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Datetime,,,,,,,
2023-10-30 09:15:00+05:30,970.000000,973.700012,954.549988,968.950012,0,0.0,0.0
2023-10-30 10:15:00+05:30,969.250000,974.200012,966.250000,966.250000,32572,0.0,0.0
2023-10-30 11:15:00+05:30,965.500000,969.799988,963.000000,965.849976,16767,0.0,0.0
2023-10-30 12:15:00+05:30,965.700012,967.500000,959.000000,961.799988,15256,0.0,0.0
2023-10-30 13:15:00+05:30,960.599976,966.049988,960.000000,965.450012,14468,0.0,0.0
...,...,...,...,...,...,...,...
2023-12-01 11:15:00+05:30,1201.050049,1206.599976,1197.000000,1199.949951,119897,0.0,0.0
2023-12-01 12:15:00+05:30,1199.949951,1204.949951,1199.050049,1203.500000,111878,0.0,0.0
2023-12-01 13:15:00+05:30,1203.650024,1211.949951,1202.000000,1208.900024,145231,0.0,0.0
2023-12-01 14:15:00+05:30,1209.300049,1230.949951,1207.000000,1223.000000,742347,0.0,0.0
2023-12-01 15:15:00+05:30,1223.599976,1226.699951,1216.000000,1224.400024,186238,0.0,0.0